import React from "react";
import { DocsThemeConfig } from "nextra-theme-docs";
import starter from "./starter.config";

const config: DocsThemeConfig = {
  logo: <span className="font-bold text-xl">{starter.title}</span>,
  project: {
    link: starter.repository,
  },
  docsRepositoryBase: `${starter.repository}/tree/main`,
  footer: {
    text: `© ${new Date().getFullYear()} ${
      starter.title
    } Contributors | Generated by Nextra Starter`,
  },
  i18n: starter.i18n.locales.map((locale) => ({
    locale: locale.locale,
    text: locale.displayName,
  })),
  useNextSeoProps() {
    return {
      titleTemplate: `%s - ${starter.title}`,
    };
  },
  sidebar: {
    defaultMenuCollapseLevel: 1,
  },
};

export default config;
